global:
  scrape_interval: 15s

scrape_configs:
  - job_name: soketi
    metrics_path: /metrics
    basic_auth:
      username: admin
      password: admin
    static_configs:
      - targets: ['host.docker.internal:9601']
